# Generated by Django 6.0.3 on 2026-03-15 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=100)),
                ('audience', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('content_type', models.CharField(choices=[('guide', 'Guide'), ('faq', 'FAQ'), ('overview', 'Overview')], max_length=10)),
                ('visibility', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('all', 'All')], max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('body_markdown', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('owner', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('sort_order', models.IntegerField(default=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('last_reviewed_at', models.DateField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='helpcenter.collection')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('collection', 'slug')},
            },
        ),
    ]
